version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./ssl:/ssl
      - ./ca:/csr
      - ./ssl:/opt/wott/certs:ro
    command: |
      bash -c "bootstrap.sh && /start.sh"
    ports:
      - '8888:8888'
    hostname: wott-ca
    networks:
      default:
        aliases:
          - wott-ca

networks:
  default:
    external:
      name: wott